---
# Source: demoapp/charts/lambda/templates/lambda-event-source-mapping.yaml
# Source: demoapp/charts/lambda/templates/lambda.yaml
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: EventSourceMapping
metadata:
  name: prod-lambda
  namespace: ack-lambda
  annotations:
    services.k8s.aws/region: us-east-1
spec:
  functionName: prod-lambda
  eventSourceARN: 
  batchSize: 10
