---
# Source: demoapp/charts/api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: moyin-demo-app
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: moyin-demo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: moyin-demo-app
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: api
          envFrom:
            - configMapRef:
                name: api
          securityContext:
            {}
          image: "975050185389.dkr.ecr.us-east-1.amazonaws.com/prod/api:86fac5d1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/metrics
              port: http
          readinessProbe:
            httpGet:
              path: /api/metrics
              port: http
          resources:
            {}
